### ISSUE TITLE
waymo config

### ISSUE THREAD

**Issue by WWW2323** [skyhehe123/VoxSeT#1]
Hi,  I  don't find waymo config of VoxSeT in the code, can the kitti config of VoxSeT be directly used for waymo dataset? thanks~

**Comment by Trent-tangtao** [comment]
Looking forward to the reply, too ~

**Comment by xiangruhuang** [comment]
Same here.

**Comment by skyhehe123** [comment]
@WWW2323 @Trent-tangtao @xiangruhuang I update the single-stage VoxSeT on Waymo.
