### ISSUE TITLE
 'batch_first'

### ISSUE THREAD

**Issue by kuaiqushangzixiba** [skyhehe123/VoxSeT#2]
1.python train.py --cfg_file cfgs/kitti_models/voxset.yaml
  File "/OpenPCDet/pcdet/models/backbones_3d/vfe/voxset.py", line 168, in __init__
    self.mhsa = nn.MultiheadAttention(dim, num_heads=1, batch_first=True) 
TypeError: __init__() got an unexpected keyword argument 'batch_first'
2.python setup.py build_dist --inplace
 error: invalid command 'build_dist'

how can i fit it ?

**Comment by kuaiqushangzixiba** [comment]
If I comment " batch_first=True" out, it appears 
  File "site-packages/torch/nn/functional.py", line 4790, in multi_head_attention_forward
    attn_output_weights = torch.bmm(q, k.transpose(1, 2))
RuntimeError: CUDA error: device-side assert triggered

**Comment by skyhehe123** [comment]
@kuaiqushangzixiba It can be solved by update the pytorch > 1.7 which support batch_first parameters.
