### ISSUE TITLE
SparseTensor fail

### ISSUE THREAD

**Issue by DezeZhao** [skyhehe123/VoxSeT#20]
https://github.com/skyhehe123/VoxSeT/blob/690482f69159a9d784c299df67d62f134e8beecd/pcdet/models/backbones_3d/vfe/voxset.py#L181
https://github.com/skyhehe123/VoxSeT/blob/690482f69159a9d784c299df67d62f134e8beecd/pcdet/models/backbones_3d/vfe/voxset.py#L84

**Comment by DezeZhao** [comment]
Line 181: fail while running, because  Line 84 calculate coords appears 0 and 1 in z axis; while your cfg file is PointPillar, z axis should always be 0, bev_shape = [216, 248, 1], z axis should only be 0;  coords.int() has 0 or 1 in z axis;

**Comment by DezeZhao** [comment]
could you help me? how to solve it ? thank u.

**Comment by DezeZhao** [comment]
solve it by clamp point cloud range

**Comment by aniket-gupta1** [comment]
@DezeZhao Can you elaborate on how did you solve it?

**Comment by DezeZhao** [comment]
> 

you can see it at this PR：https://github.com/skyhehe123/VoxSeT/pull/21/commits/3eadaff219f50c8439f18f3e46274552a608d3cc
