### ISSUE TITLE
error: invalid command 'build_dist'

### ISSUE THREAD

**Issue by libingDY** [skyhehe123/VoxSeT#4]
python setup.py build_dist --inplace
/home/libing/anaconda3/envs/yolo3d/lib/python3.6/site-packages/setuptools/dist.py:458: UserWarning: Normalizing '0.5.2+0000000' to '0.5.2+0'
  warnings.warn(tmpl.format(**locals()))
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: invalid command 'build_dist'

How can I solve this problem？

**Comment by skyhehe123** [comment]
> 

It should be python setup.py build_ext --inplace
