### ISSUE TITLE
codes issue

### ISSUE THREAD

**Issue by Z-Lee-corder** [skyhehe123/VoxSeT#7]
Hi, I tried to run your code, but some error occurred:
Traceback (most recent call last):
  File "/media/lizheng/datum/codes/VoxSeT/tools/train.py", line 203, in <module>
    main()
  File "/media/lizheng/datum/codes/VoxSeT/tools/train.py", line 117, in main
    model = build_network(model_cfg=cfg.MODEL, num_class=len(cfg.CLASS_NAMES), dataset=train_set)
  File "../pcdet/models/__init__.py", line 18, in build_network
    model_cfg=model_cfg, num_class=num_class, dataset=dataset
  File "../pcdet/models/detectors/__init__.py", line 30, in build_detector
    model_cfg=model_cfg, num_class=num_class, dataset=dataset
  File "../pcdet/models/detectors/pointpillar.py", line 7, in __init__
    self.module_list = self.build_networks()
  File "../pcdet/models/detectors/detector3d_template.py", line 47, in build_networks
    model_info_dict=model_info_dict
  File "../pcdet/models/detectors/detector3d_template.py", line 62, in build_vfe
    depth_downsample_factor=model_info_dict['depth_downsample_factor']
  File "../pcdet/models/backbones_3d/vfe/voxset.py", line 41, in __init__
    self.mlp_vsa_layer_0 = MLP_VSA_Layer(self.input_dim * 1, self.num_latents[0])
  File "../pcdet/models/backbones_3d/vfe/voxset.py", line 168, in __init__
    self.mhsa = nn.MultiheadAttention(dim, num_heads=1, batch_first=True) 
TypeError: __init__() got an unexpected keyword argument 'batch_first'

my environment : python==3.8,  torch=1.7.1
Is the problem caused by the low version of torch or something else?

**Comment by skyhehe123** [comment]
> Hi, I tried to run your code, but some error occurred: Traceback (most recent call last): File "/media/lizheng/datum/codes/VoxSeT/tools/train.py", line 203, in main() File "/media/lizheng/datum/codes/VoxSeT/tools/train.py", line 117, in main model = build_network(model_cfg=cfg.MODEL, num_class=len(cfg.CLASS_NAMES), dataset=train_set) File "../pcdet/models/**init**.py", line 18, in build_network model_cfg=model_cfg, num_class=num_class, dataset=dataset File "../pcdet/models/detectors/**init**.py", line 30, in build_detector model_cfg=model_cfg, num_class=num_class, dataset=dataset File "../pcdet/models/detectors/pointpillar.py", line 7, in **init** self.module_list = self.build_networks() File "../pcdet/models/detectors/detector3d_template.py", line 47, in build_networks model_info_dict=model_info_dict File "../pcdet/models/detectors/detector3d_template.py", line 62, in build_vfe depth_downsample_factor=model_info_dict['depth_downsample_factor'] File "../pcdet/models/backbones_3d/vfe/voxset.py", line 41, in **init** self.mlp_vsa_layer_0 = MLP_VSA_Layer(self.input_dim * 1, self.num_latents[0]) File "../pcdet/models/backbones_3d/vfe/voxset.py", line 168, in **init** self.mhsa = nn.MultiheadAttention(dim, num_heads=1, batch_first=True) TypeError: **init**() got an unexpected keyword argument 'batch_first'
> 
> my environment : python==3.8, torch=1.7.1 Is the problem caused by the low version of torch or something else?

This is because pytorch1.7 does not support this argument. I suggest a updated version of pytorch, e.g. 1.9
